language: rust
rust:
  - stable
  - beta
  - nightly
os:
  - linux
  - osx
script:
  - cargo build --release --all --verbose
  - cargo test --release --all --verbose
matrix:
  allow_failures:
    - rust: nightly
