language: rust

rust:
  - stable
  - beta
  - nightly

os:
  - linux
  - osx

script:
  - cargo build --release --all --verbose
  - cargo test --release --all --verbose

matrix:
  allow_failures:
    - rust: nightly

before_deploy:
  - sh .ci/before_deploy.sh

notifications:
  email:
    on_success: never
