language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly
os:
  - linux
script:
  - |
    export PATH="$PATH":~/.cargo/bin &&
    export RUST_BACKTRACE=1 &&
    cargo build &&
    cargo test --verbose &&
    cargo doc --no-deps &&
    cd src/bin/gaslighter &&
    git clone https://github.com/ethereumproject/tests.git &&
    cd tests &&
    git checkout develop &&
    cd .. &&
    cargo build &&
    cargo run -- crat -f tests/VMTests/vmArithmeticTest.json &&
    cargo run -- crat -f tests/VMTests/vmBitwiseLogicOperationTest.json &&
    cargo run -- crat -f tests/VMTests/vmBlockInfoTest.json &&
    cargo run -- crat -f tests/VMTests/vmIOandFlowOperationsTest.json &&
    cargo run -- crat -f tests/VMTests/vmLogTest.json &&
    cargo run -- crat -f tests/VMTests/vmPerformanceTest.json &&
    cargo run -- crat -f tests/VMTests/vmPushDupSwapTest.json &&
    cargo run -- crat -f tests/VMTests/vmSha3Test.json &&
    cargo run -- crat -f tests/VMTests/vmEnvironmentalInfoTest.json

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev

after_success: |
  ls -la &&
  ls -la target &&
  ls -la target/debug/ &&
  wget https://github.com/SimonKagstrom/kcov/archive/v33.tar.gz &&
  tar xzf v33.tar.gz &&
  cd kcov-33 &&
  mkdir build &&
  cd build &&
  cmake .. &&
  make &&
  sudo make install &&
  cd ../.. &&
  rm -rf kcov-33 &&
  cat /home/travis/.travis/job_stages &&
  kcov --exclude-pattern=/.cargo,/usr/lib --verify target/cov target/debug/gaslighter &&
  bash <(curl -s https://codecov.io/bash) &&
  echo "Uploaded code coverage"
matrix:
  allow_failures:
    - rust: nightly
notifications:
  email:
    on_success: never
