dist: trusty
language: rust
cache: cargo
sudo: true
rust:
  - stable
  - beta
  - nightly
os:
  - linux

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - libiberty-dev
      - g++

script:
  - |
    export PATH="$PATH":~/.cargo/bin &&
    export RUST_BACKTRACE=1 &&
    cd gaslighter &&
    cargo build &&
    cargo test --verbose &&
    cargo doc --no-deps &&
    git clone https://github.com/ethereumproject/tests.git &&
    cd tests &&
    git checkout develop &&
    cd .. &&
    cargo run -- crat -f tests/VMTests/vmArithmeticTest.json &&
    cargo run -- crat -f tests/VMTests/vmBitwiseLogicOperationTest.json &&
    cargo run -- crat -f tests/VMTests/vmBlockInfoTest.json &&
    cargo run -- crat -f tests/VMTests/vmIOandFlowOperationsTest.json &&
    cargo run -- crat -f tests/VMTests/vmLogTest.json &&
    cargo run -- crat -f tests/VMTests/vmPerformanceTest.json &&
    cargo run -- crat -f tests/VMTests/vmPushDupSwapTest.json &&
    cargo run -- crat -f tests/VMTests/vmSha3Test.json &&
    cargo run -- crat -f tests/VMTests/vmEnvironmentalInfoTest.json &&
    cd .. &&
    cargo install cargo-kcov &&
    cargo-kcov kcov --all  -- --no-clean-rebuild --lib --coveralls

install:
  - rustc -vV
  - cargo -vV
  - mkdir -p ~/.cargo/bin
  - sh .coverage/install_kcov.sh
  - export PATH=$HOME/.local/bin:$HOME/.cargo/bin:$HOME/Library/Python/2.7/bin:$PATH
  - export RUSTFLAGS="-C link-dead-code"
  - kcov --version

matrix:
  allow_failures:
    - rust: nightly
notifications:
  email:
    on_success: never
