language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly
os:
  - linux
script:
  - |
    export PATH="$PATH":~/.cargo/bin &&
    export RUST_BACKTRACE=1 &&
    (test "$TRAVIS_RUST_VERSION" == nightly || cargo build --verbose --release) &&
    cargo test --verbose &&
    cargo doc --no-deps
matrix:
  allow_failures:
    - rust: nightly
notifications:
  email:
    on_success: never
