language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly
os:
  - linux
script:
  - |
    export PATH="$PATH":~/.cargo/bin &&
    export RUST_BACKTRACE=1 &&
    cargo build &&
    cargo test --verbose &&
    cargo doc --no-deps &&
    cd src/bin/gaslighter &&
    cargo build
matrix:
  allow_failures:
    - rust: nightly
notifications:
  email:
    on_success: never
