language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly
os:
  - linux
script:
  - |
    export PATH="$PATH":~/.cargo/bin &&
    export RUST_BACKTRACE=1 &&
    cd gaslighter &&
    cargo build &&
    cargo test --verbose &&
    cargo doc --no-deps &&
    git clone https://github.com/ethereumproject/tests.git &&
    cd tests &&
    git checkout develop &&
    cd .. &&
    cargo run -- crat -f tests/VMTests/vmArithmeticTest.json &&
    cargo run -- crat -f tests/VMTests/vmBitwiseLogicOperationTest.json &&
    cargo run -- crat -f tests/VMTests/vmBlockInfoTest.json &&
    cargo run -- crat -f tests/VMTests/vmIOandFlowOperationsTest.json &&
    cargo run -- crat -f tests/VMTests/vmLogTest.json &&
    cargo run -- crat -f tests/VMTests/vmPerformanceTest.json &&
    cargo run -- crat -f tests/VMTests/vmPushDupSwapTest.json &&
    cargo run -- crat -f tests/VMTests/vmSha3Test.json &&
    cargo run -- crat -f tests/VMTests/vmEnvironmentalInfoTest.json &&
    cd ..

addons:
  apt:
    packages:
      - kcov

after_success: |
  kcov --exclude-pattern=/.cargo,/usr/lib --verify target/cov target/debug/gaslighter &&
  bash <(curl -s https://codecov.io/bash) &&
  echo "Uploaded code coverage"

matrix:
  allow_failures:
    - rust: nightly
notifications:
  email:
    on_success: never
