[package]
name = "evm"
version = "0.13.1"
license = "Apache-2.0"
authors = ["Wei Tang <hi@that.world>", "Parity Technologies <admin@parity.io>"]
description = "SputnikVM - a Portable Blockchain Virtual Machine"
repository = "https://github.com/sorpaas/rust-evm"
keywords = ["no_std", "ethereum"]
edition = "2018"

[dependencies]
evm-core = { version = "0.13", path = "core", default-features = false }
evm-gasometer = { version = "0.13", path = "gasometer", default-features = false }
evm-runtime = { version = "0.13", path = "runtime", default-features = false }
sha3 = { version = "0.8", default-features = false }
rlp = { version = "0.4", default-features = false }
primitive-types = { version = "0.6", default-features = false, features = ["impl-rlp"] }

[features]
default = ["std"]
std = ["evm-core/std", "evm-gasometer/std", "evm-runtime/std", "sha3/std", "primitive-types/std"]

[workspace]
members = [
  "core",
  "gasometer",
  "runtime",
  "jsontests",
]
