[package]
name = "sputnikvm"
version = "0.6.2"
license = "Apache-2.0"
authors = ["Wei Tang <hi@that.world>"]
description = "SputnikVM - a Portable Blockchain Virtual Machine"
repository = "https://github.com/ethereumproject/sputnikvm"

[lib]
name = "sputnikvm"
crate-type = ["rlib", "cdylib"]

[dependencies]
log = "0.3"
ripemd160 = "0.6"
sha2 = "0.6"
sha3 = "0.6"
digest = { version = "0.6", features = ["std"]}
lazy_static = "0.2"
secp256k1-plus = "0.5.7"
etcommon-block = "0.2"
etcommon-rlp = "0.2"
etcommon-bigint = "0.2"
etcommon-hexutil = "0.2"

[workspace]
members = [
  "./jsontests",
  "./regtests",
  "./gethrpc",
  "./stateful",
]
