[package]
name = "sputnikvm"
version = "0.1.0"
license = "Apache-2.0"
authors = ["Stewart Mackenzie <setori88@gmail.com>", "Wei Tang <hi@that.world>"]
description = "SputnikVM - the Ethereum Classic Virtual Machine"

[lib]
name = "sputnikvm"
path = "./src/lib.rs"
crate-type = ["rlib", "dylib"]

[[bin]]
name = "svm"
path = "./src/bin/cli.rs"

[[bin]]
name = "gaslighter"
path = "./src/bin/gaslighter/mod.rs"

[dependencies]
clap = "2.22"
log = "0.3"
capnp = "0.8"
rust-crypto = "^0.2"
merkle = { git = "https://github.com/sorpaas/merkle.rs", branch = "sha3" }