[package]
name = "sputnikvm"
version = "0.1.0"
license = "Apache-2.0"
authors = ["Stewart Mackenzie <setori88@gmail.com>", "Wei Tang <hi@that.world>"]
description = "SputnikVM - the Ethereum Classic Virtual Machine"

[lib]
name = "sputnikvm"
path = "./src/lib.rs"
crate-type = ["rlib", "cdylib"]

[[bin]]
name = "svm"
path = "./src/bin/cli/mod.rs"

[[bin]]
name = "gaslighter"
path = "./src/bin/gaslighter/mod.rs"

[[bin]]
name = "jsonlighter"
path = "./src/bin/jsonlighter/mod.rs"

[dependencies]
clap = "2.22"
log = "0.3"
capnp = "0.8"
rust-crypto = "^0.2"
merkle-sha3 = "0.1"
libc = "0.2"
libloading = "0.3"
serde_json = "0.9"
