[package]
name = "bigint2"
version = "0.1.0"
authors = ["Wei Tang <hi@that.world>", "Stewart Mackenzie <setori88@gmail.com>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/ethereumproject/sputnikvm"
description = "Large fixed-size integers arithmetics"

[dependencies]
rlp2 = "0.2.0"
