[package]
name = "evm-fuzzer"
version = "0.1.0"
authors = ["Vincent Ulitzsch <vincent@srlabs.de>"]
edition = "2018"

[dependencies]
honggfuzz = "0.5"
evm-core = { version = "0.29", path= "../core" }

[[bin]]
name = "evm_fuzz"
path = "src/main.rs"
