[package]
name = "sputnikvm-cli"
version = "0.3.0"
license = "Apache-2.0"
authors = ["Wei Tang <hi@that.world>"]
description = "SputnikVM CLI"
repository = "https://github.com/ethereumproject/sputnikvm"

[dependencies]
