[package]
name = "jsontests"
version = "0.6.0"
license = "Apache-2.0"
authors = ["Stewart Mackenzie <setori88@gmail.com>", "Wei Tang <hi@that.world>"]

[dependencies]
sputnikvm = { path = '..' }
serde_json = "1.0"
lazy_static = "0.2"
