[package]
name = "regtests"
version = "0.3.0"
license = "Apache-2.0"
authors = ["Stewart Mackenzie <setori88@gmail.com>", "Wei Tang <hi@that.world>"]
description = "regtests - performs a regression test of the entire ethereum classic blockchain."

[[bin]]
name = "regtests"

[dependencies]
sputnikvm = { path = '..' }
gethrpc = { path = '../gethrpc' }
clap = "2.22"
serde_json = "0.9"
