[package]
name = "evm-precompiled-bn128"
version = "0.10.1"
description = "bn128 precompiled contracts for SputnikVM."
license = "Apache-2.0"
authors = ["Wei Tang <hi@that.world>"]
repository = "https://github.com/etclabscore/sputnikvm"

[dependencies]
evm = { version = "0.10", path = "../..", default-features = false }
ethereum-bigint = { version = "0.2", default-features = false }
bn = { version = "0.4", git = "https://github.com/etclabscore/bn.git", rev = "a604e5da959e1878318c8eea5219d90d6a28f578", default-features = false }

[features]
default = ["std", "rust-secp256k1"]
rlp = ["ethereum-bigint/rlp"]
c-secp256k1 = ["evm/c-secp256k1"]
rust-secp256k1 = ["evm/rust-secp256k1"]
std = ["evm/std", "bn/std"]
