[package]
name = "evm-precompiled-bn128"
version = "0.10.0"
description = "bn128 precompiled contracts for SputnikVM."
license = "Apache-2.0"
authors = ["Wei Tang <hi@that.world>"]
repository = "https://source.that.world/source/evm-rs"

[dependencies]
evm = { version = "0.10", path = "../.." }
ethereum-bigint = { version = "0.2", default-features = false }
bn-plus = { version = "0.4" }
