[package]
name = "evm-precompiled-modexp"
version = "0.10.0"
description = "modexp precompiled contracts for SputnikVM."
license = "Apache-2.0"
authors = ["Wei Tang <hi@that.world>"]
repository = "https://source.that.world/source/evm-rs"

[dependencies]
evm = { version = "0.10", path = "../..", default-features = false  }
ethereum-bigint = { version = "0.2", default-features = false }
num-bigint = "0.1"

[dev-dependencies]
ethereum-hexutil = "0.2"

[features]
default = ["std", "rust-secp256k1"]
rlp = ["ethereum-bigint/rlp"]
c-secp256k1 = ["evm/c-secp256k1"]
rust-secp256k1 = ["evm/rust-secp256k1"]
std = ["evm/std"]
